spring:
  config:
    name: production
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    contexts: production
  datasource:
    username: 'fund_raiser_server'
    password: 'frs123'
    url: jdbc:postgresql://db-postgres:5432/fund_raiser

image-repository-path: 'opt/app-root/src/image-repository/'
