server:
  servlet:
    context-path: '/api'
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

image-repository-path: 'image-repository/'
